# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - echo "For start pipeline start in shell 'task run:<role_name>:<inventory_file_without_ext>'"
      - echo "Current ansible roles"
      - echo " - bootstrap"
      - echo " - docker"
      - echo " - pam-events"
      - echo " - production"
      - echo " - test"
      - echo " - upgrade"
      - echo " - wg"
    silent: true

  run:*:*:
    vars:
      my_hosts: "{{index .MATCH 1}}"
      my_role: "{{index .MATCH 0}}"
    cmds:
      - ansible-playbook -i inventory/{{ .my_hosts }}.ini {{ .my_role }}.yml
