# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  upgrade:*:
    vars:
      my_hosts: "{{index .MATCH 0}}"
    cmds:
      - ansible-playbook -i inventory/{{ .my_hosts }}.ini upgrade.yml

  pam-events:*:
    vars:
      my_hosts: "{{index .MATCH 0}}"
    cmds:
      - ansible-playbook -i inventory/{{ .my_hosts }}.ini pam-events.yml

  wg:*:
    vars:
      my_hosts: "{{index .MATCH 0}}"
    cmds:
      - ansible-playbook -i inventory/{{ .my_hosts }}.ini wireguard.yml
