# SPDX-License-Identifier: MIT-0
---
# handlers file for base-config
- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: Restart ufw
  ansible.builtin.service:
    name: ufw
    state: restarted
