# SPDX-License-Identifier: MIT-0
---
# tasks file for pam-events
- name: Create script for send alerts
  ansible.builtin.template:
    src: "tg_alert.sh.j2"
    dest: "{{ pam_event_script_url }}"
    mode: "0611"

- name: Add event on auth
  ansible.builtin.lineinfile:
    dest: /etc/pam.d/sshd
    line: "session required pam_exec.so {{ pam_event_script_url }}"
    state: present
    insertafter: EOF
