# SPDX-License-Identifier: MIT-0
---
# vars file for bootstrap-server
fail2ban_alpine_sshd_configuration:
  - option: enabled
    value: true
    section: sshd
  - option: filter
    value: alpine-sshd
    section: sshd
  - option: port
    value: "{{ ssh_desired_port }}"
    section: sshd
  - option: logpath
    value: /var/log/messages
    section: sshd
  - option: maxretry
    value: "{{ fail2ban_sshd_maxretries }}"
    section: sshd
  - option: bantime
    value: "{{ fail2ban_sshd_bantime }}"
    section: sshd

fail2ban_alpine_sshd_ddos_configuration:
  - option: enabled
    value: true
    section: sshd-ddos
  - option: filter
    value: alpine-sshd-ddos
    section: sshd-ddos
  - option: port
    value: "{{ ssh_desired_port }}"
    section: sshd-ddos
  - option: logpath
    value: /var/log/messages
    section: sshd-ddos
  - option: maxretry
    value: "{{ fail2ban_sshd_ddos_maxretries }}"
    section: sshd-ddos
  - option: bantime
    value: "{{ fail2ban_sshd_bantime }}"
    section: sshd-ddos
