---
- name: Check if ssh is running on {{ ssh_desired_port }}
  ansible.builtin.wait_for:
    port: "{{ ssh_desired_port }}"
    host: "{{ ansible_host }}"
    timeout: 10
  ignore_errors: true
  register: desired_port_check

- name: Check if ssh is running on {{ ssh_default_port }}
  ansible.builtin.wait_for:
    port: "{{ ssh_default_port }}"
    host: "{{ ansible_host }}"
    timeout: 10
  ignore_errors: true
  register: default_port_check

- name: SSH port not found 
  ansible.builtin.fail:
    msg: "ssh is not running (or is running on an unknown port)"
  when: default_port_check is failed and desired_port_check is failed

- name: Setup alternate sshd port
  ansible.builtin.lineinfile:
    dest: "{{ sshd_config_path }}"
    regexp: "^Port"
    line: "Port {{ ssh_desired_port }}"
  with_items: "{{ sshd_config_path }}"
  when: default_port_check is success and ssh_default_port != ssh_desired_port
  register: ssh_config
