# SPDX-License-Identifier: MIT-0
---
# tasks file for sshd-with-ports
- name: Disable include string
  ansible.builtin.lineinfile:
    path: "{{ item.path }}"
    line: "Include /etc/ssh/sshd_config.d/*.conf"
    state: absent
  with_items: "{{ sshd_config_path }}"
  register: ssh_config

- name: Deactivate PermitRootLogin
  ansible.builtin.lineinfile:
    path: "{{ item.path }}"
    line: "PermitRootLogin no"
    state: present
  with_items: "{{ sshd_config_path }}"
  register: ssh_config

- name: Ensure PermitRootLogin is not enabled
  ansible.builtin.lineinfile:
    path: "{{ item.path }}"
    line: "PermitRootLogin yes"
    state: absent
  with_items: "{{ sshd_config_path }}"
  register: ssh_config

- name: Deactivate PasswordAuthentication
  ansible.builtin.lineinfile:
    path: "{{ item.path }}"
    line: "PasswordAuthentication no"
    state: present
  with_items: "{{ sshd_config_path }}"
  register: ssh_config

- name: Ensure PasswordAuthentication is not enabled
  ansible.builtin.lineinfile:
    path: "{{ item.path }}"
    line: "PasswordAuthentication yes"
    state: absent
  with_items: "{{ sshd_config_path }}"
  register: ssh_config

- name: Activate PubkeyAuthentication
  ansible.builtin.lineinfile:
    path: "{{ item.path }}"
    line: "PubkeyAuthentication yes"
    state: present
  with_items: "{{ sshd_config_path }}"
  register: ssh_config

- name: Ensure PubkeyAuthentication is not disabled
  ansible.builtin.lineinfile:
    path: "{{ item.path }}"
    line: "PubkeyAuthentication no"
    state: absent
  with_items: "{{ sshd_config_path }}"
  register: ssh_config

- name: Change sshd port
  ansible.builtin.import_tasks: change-port.yml

- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
  when: ssh_config.changed or desired_port_check is failed
