---
- name: Add new user
  become: true
  ansible.builtin.user:
    append: true
    create_home: true
    groups: "{{ item.groups }}"
    local: true
    name: "{{ item.name }}"
    password: "{{ item.passwd }}"
  with_items: "{{ users_details }}"
