---
- name: Add new user
  ansible.builtin.user:
    create_home: true
    name: "{{ item.name }}"
    password: "{{ item.passwd }}"
    shell: "{{ item.shell }}"
    remove: "{{ item.remove }}"
    state: "{{ item.state }}"
  with_items: "{{ users_details }}"
