---
- name: Configuration jail.d/alpine-ssh.conf
  community.general.ini_file:
    backup: true
    path: /etc/fail2ban/jail.d/alpine-ssh.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    mode: "0640"
  loop: "{{ fail2ban_alpine_sshd_configuration + fail2ban_alpine_sshd_ddos_configuration }}"
  loop_control:
    label: "{{ item.option }}"
  notify:
    - Restart fail2ban
 