---
- name: Get current arch
  ansible.builtin.command:
    cmd: dpkg --print-architecture
  register: arch

- name: Add PGP key to apt
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: "{{ docker_keyring }}"
    mode: '0644'

- name: Add docker repository to apt
  ansible.builtin.apt_repository:
    filename: docker
    repo: "deb [arch={{ arch.stdout }} signed-by={{ docker_keyring }}] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    update_cache: true
