---
- name: Add ssh key to user
  ansible.posix.authorized_key:
    key: "{{ item.key }}"
    user: "{{ item.user }}"
    comment: "{{ item.comment }}"
    manage_dir: true
  with_items: "{{ user_ssh_keys }}"
