---
- name: Configuration jail.local
  community.general.ini_file:
    backup: true
    path: /etc/fail2ban/jail.local
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    mode: "0640"
  loop: "{{ fail2ban_default_option + fail2ban_sshd_option }}"
  loop_control:
    label: "{{ item.option }}"
  notify:
    - Restart fail2ban
