# SPDX-License-Identifier: MIT-0
---
# tasks file for bootstrap-server
- name: Disable IPv6
  ansible.builtin.import_tasks: disable-ipv6.yml

- name: Add users
  ansible.builtin.import_tasks: add-user.yml

- name: Add existing user to groups
  ansible.builtin.import_tasks: user-to-groups.yml

- name: Add group to sudoers
  ansible.builtin.import_tasks: sudoers-group.yml

- name: Add sshkey for users
  ansible.builtin.import_tasks: authkey-user.yml

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install base system soft
  ansible.builtin.import_tasks: install-base-soft.yml

- name: Configuration fail2ban
  ansible.builtin.import_tasks: alpine-fail2ban.yml
  when: ansible_distribution == 'Alpine' and 'fail2ban' in ansible_facts.packages

- name: Add settings for UFW
  ansible.builtin.import_tasks: ufw.yml
  when: "'ufw' in ansible_facts.packages"

- name: Start and enabled services
  ansible.builtin.import_tasks: service-enabled.yml
