---
- name: Add user to sudoers without password needed
  community.general.sudoers:
    name: 00-wheel-users
    commands: "{{ item.commands }}"
    host: "{{ item.host }}"
    group: "{{ item.group }}"
    state: present
    runas: "{{ item.runas }}"
  with_items: "{{ sudoers_groups }}"
