---
- name: Set default policy
  community.general.ufw:
    default: reject

- name: Allow everything and enable UFW
  community.general.ufw:
    state: enabled

- name: Set logging
  community.general.ufw:
    logging: "on"

- name: Add access port for traffic
  community.general.ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    direction: "{{ item.direction }}"
  with_items: "{{ ufw_allowed_traffics }}"
  notify:
    - Restart ufw

- name: Disable ipv6
  ansible.builtin.lineinfile:
    backup: true
    line: "IPV6=no"
    path: /etc/default/ufw
    regexp: "IPV6=yes"
    state: present
