# SPDX-License-Identifier: MIT-0
galaxy_info:
  author: Artem Misko
  description: Role for install and configuration docker
  license: MIT

  min_ansible_version: "2.11"

  galaxy_tags: []

dependencies: []
